### ISSUE TITLE
Allow user to specify PR number

### ISSUE THREAD

**Issue by Jameskmonger** [riskledger/update-pr-description#39]
It would be really useful to have the option of specifying a PR number as an argument to the action

e.g.

```yaml
  - uses: riskledger/update-pr-description@dev
    with:
      prNum: 1234
      body: ${{ description }}
      token: ${{ secrets.GITHUB_TOKEN }}
```

The default behaviour could be preserved if no argument is given
